export type Hotel = {
  name: string;
  tier: string;
  region: string;
};

export const hotels: Hotel[] = [
  { name: "Aman Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Bulgari Hotel Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Conrad Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Four Seasons Hotel Tokyo at Otemachi", tier: "luxury-center", region: "tokyo" },
  { name: "Hyatt Centric Ginza Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Imperial Hotel Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Mandarin Oriental Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Oakwood Premier Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Palace Hotel Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "Shangri-La Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "The Peninsula Tokyo", tier: "luxury-center", region: "tokyo" },
  { name: "The Tokyo EDITION, Ginza", tier: "luxury-center", region: "tokyo" },
  { name: "The Tokyo Station Hotel", tier: "luxury-center", region: "tokyo" },

  { name: "Andaz Tokyo — A Concept by Hyatt", tier: "luxury-other", region: "tokyo" },
  { name: "Grand Hyatt Tokyo (Roppongi)", tier: "luxury-other", region: "tokyo" },
  { name: "Janu Tokyo", tier: "luxury-other", region: "tokyo" },
  { name: "Hotel Toranomon Hills, The Unbound Collection By Hyatt", tier: "luxury-other", region: "tokyo" },
  { name: "Mesm Tokyo, Autograph Collection (Takeshiba)", tier: "luxury-other", region: "tokyo" },
  { name: "Ritz Carlton Tokyo (Roppongi)", tier: "luxury-other", region: "tokyo" },
  { name: "The Okura Tokyo", tier: "luxury-other", region: "tokyo" },
  { name: "The Prince Gallery Tokyo Kioicho, a Luxury Collection Hotel (Akasaka)", tier: "luxury-other", region: "tokyo" },
  { name: "The Tokyo EDITION, Toranomon", tier: "luxury-other", region: "tokyo" },

  { name: "Dai-Ichi Hotel Tokyo", tier: "premium", region: "tokyo" },
  { name: "Mercure Tokyo Hibiya", tier: "premium", region: "tokyo" },
  { name: "Ginza Hotel by Granbell", tier: "premium", region: "tokyo" },
  { name: "The Royal Park Canvas Ginza Corridor", tier: "premium", region: "tokyo" },
  { name: "The Royal Park Hotel Ginza 6-Chome", tier: "premium", region: "tokyo" },
  { name: "Hotel GrandBach Tokyo Ginza", tier: "premium", region: "tokyo" },
  { name: "Mitsui Garden Hotel Ginza Premier", tier: "premium", region: "tokyo" },
  { name: "The Gate Hotel Tokyo by Hulic", tier: "premium", region: "tokyo" },
  { name: "Hotel The Celestine Ginza", tier: "premium", region: "tokyo" },
  { name: "The Blossom Hibiya", tier: "premium", region: "tokyo" },
  { name: "Millennium Mitsui Garden Hotel Tokyo", tier: "premium", region: "tokyo" },
  { name: "Karaksa Hotel Premier Tokyo Ginza", tier: "premium", region: "tokyo" },
  { name: "Muji Hotel Ginza", tier: "premium", region: "tokyo" },
  { name: "The Royal Park Hotel Iconic Tokyo Shiodome", tier: "premium", region: "tokyo" },
  { name: "Hotel Metropolitan Tokyo Marunouchi", tier: "premium", region: "tokyo" },
  { name: "Ginza Creston", tier: "premium", region: "tokyo" },
  { name: "Dormy Inn Premium Ginza Natural Hot Spring", tier: "premium", region: "tokyo" },

  { name: "Ginza Grand Hotel", tier: "economy-premium", region: "tokyo" },
  { name: "Agora Tokyo Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "Hotel Keihan Tsukiji Ginza Grande", tier: "economy-premium", region: "tokyo" },
  { name: "KOKO HOTEL Tsukiji Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "MONday Apart Premium Nihonbashi", tier: "economy-premium", region: "tokyo" },
  { name: "Solaria Nishitetsu Hotel Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "Hotel Gracery Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "Remm Hibiya", tier: "economy-premium", region: "tokyo" },
  { name: "Remm plus Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "Remm Tokyo Kyobashi", tier: "economy-premium", region: "tokyo" },
  { name: "Hotel Musse Ginza Meitetsu", tier: "economy-premium", region: "tokyo" },
  { name: "Daiwa Roynet Hotel Ginza", tier: "economy-premium", region: "tokyo" },
  { name: "Daiwa Roynet Hotel Shinbashi", tier: "economy-premium", region: "tokyo" },
  { name: "Sotetsu Fresa Inn Ginza-Nanachome", tier: "economy-premium", region: "tokyo" },
  { name: "Sotetsu Fresa Inn Ginza-Sanchome", tier: "economy-premium", region: "tokyo" },
  { name: "the b ginza", tier: "economy-premium", region: "tokyo" },
];
